baseurl = "https://wingsopenwide.org.uk/"
languageCode = "en-us"
title = "wings open wide"
theme = "wow-theme"
copyright = "This work is licensed under a Creative Commons Attribution-Non-Commercial ShareAlike 4.0 International License."

[taxonomies]
	tag = "tags"
	album = "albums"

# Enable comments by entering your Disqus shortname
#disqusShortname = "spf13"
# Add your tracking code to enable Google Analytics
googleAnalytics = ""
# Posts per page
paginate = 20


[params]
	author = "bsag"
	description = "A collection of photographs that I'm relatively proud of."
	imgurl = "https://wingsopenwide-images.s3.amazonaws.com/"
	thumbimgurl = "https://wingsopenwide-images.s3.amazonaws.com/thumbs/"
	comments = true
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	gravatar = "butshesagirl@rousette.org.uk"
	# or use Gravatar by adding your email address to generate a unique avatar
	#gravatar = "your@email.com"

	copyright = '<a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA Licence</a>'


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "butshesagirl@rousette.org.uk"
		flickr = "bsag"
		github = "bsag"
		instagram = "bsag"
		pinterest = "bsag"
		twitter = "https://twitter.com/bsag/"

	[params.staticman]
		api = "https://api.staticman.net/v2/entry/bsag/wow/master/comments"
		pulls = "https://github.com/bsag/wow/pulls"
